"""The `init` subcommand: scaffold the adopter layout.

`init` creates the minimal layout for both layers -- curated knowledge and
agent memory -- plus the adopter's configuration and a valid declared
extension stub, so that `validate` and `lint` pass clean right after a run on
an empty project. Every item is created only if missing: an existing item is
left untouched, never overwritten or deleted, and `init` says which of the
two happened.

With `--harness-memory PATH`, `init` also makes PATH a move-proof symlink to
this project's `memory/` directory (absolute target). That is the data half
of the harness integration: computing PATH from the harness's own layout and
calling `init --harness-memory PATH` on every session start is the plugin's
startup hook, wired in a later ticket. `init` only guarantees that calling it
again -- from the same checkout or from a renamed or re-cloned one -- restores
the link without ever deleting data.

When PATH is a real path that is not a symlink, `adopt` decides: a directory
recognizably holding the harness's own agent memory is absorbed into this
project's `memory/` and parked aside as a `.bak` before the link is created
(see `adopt.py`); anything else is left alone with a WARNING saying why. Both
outcomes are fail-open, so a startup hook built on top of `init` can never
break the session.
"""

from pathlib import Path

from . import adopt
from .findings import ERROR, EXIT_ERROR, EXIT_OK, WARNING, Finding

MEMORY_INDEX = """\
# Agent memory

No entries yet.
"""

CONFIG = """\
---
extension:
  schema: knowledge-extension.md
  version: "1"
id_prefix: kb-
probes:
  git_ref: python3 -m validated_memory.probes.git_ref
---

# Adopter configuration

This file configures how `validated-memory` treats this repository. It is
plain Markdown with a YAML-subset frontmatter, readable without the plugin
installed.

- `extension` names the adopter's declared extension: the schema file
  (`schema`) and the version of it this project is on (`version`). See
  `knowledge-extension.md`.
- `id_prefix` records the id scheme curated-knowledge units follow, for
  humans and skills; `validate` does not enforce it.
- `probes` maps an anchor `kind` to the command that probes it for
  freshness. `git_ref` ships with the plugin as
  `python3 -m validated_memory.probes.git_ref`.

Generated by `validated-memory init`. Safe to hand-edit -- `init` never
overwrites a file that already exists.
"""

EXTENSION_STUB = """\
---
fields: []
---

# Declared extension

This is the adopter's curated-knowledge schema: it declares the fields a
unit's frontmatter may carry, on top of the base contract (`id`, `evidence`,
`supersedes`, `anchors`, `provenance`). No fields are declared yet
(`fields: []`) -- `validate` still enforces the base contract alone until you
add some.

Add a field as an entry under `fields`:

```yaml
fields:
  - name: domain      # the frontmatter key a unit may carry
    type: enum        # 'string' (any non-empty scalar) or 'enum' (closed domain)
    values:           # required only for type 'enum'
      - network
      - storage
  - name: owner
    type: string
```

## Versioning

`version`, in `validated-memory.md`, records which schema version this
project is on. Additive changes (a new field, a new enum value) do not bump
the version; removing or narrowing does. Units already written are never
rewritten to a newer schema -- supersede them instead.

Generated by `validated-memory init`. Safe to hand-edit -- `init` never
overwrites a file that already exists.
"""


def run(harness_memory, stdout, stderr):
    """Scaffold the adopter layout under the working directory.

    Returns an exit code: 0 unless an item could not be created. Even a
    harness-memory symlink `init` cannot restore is a WARNING, not an ERROR
    -- fail-open, so the caller (eventually a startup hook) never breaks the
    session over it.
    """
    findings = []
    created = 0
    kept = 0

    # Each call below runs (and creates its item, if missing) immediately;
    # this just names the completed results before reporting them in order.
    steps = (
        _ensure_dir(Path("knowledge")),
        _ensure_dir(Path("memory")),
        _ensure_file(Path("memory") / "MEMORY.md", MEMORY_INDEX),
        _ensure_file(Path("validated-memory.md"), CONFIG),
        _ensure_file(Path("knowledge-extension.md"), EXTENSION_STUB),
    )
    for item, outcome, finding in steps:
        if finding is not None:
            findings.append(finding)
            continue
        print(f"init: {outcome} {item}", file=stdout)
        if outcome == "created":
            created += 1
        else:
            kept += 1

    if harness_memory is not None:
        findings.extend(_sync_symlink(harness_memory, stdout))

    errors = [finding for finding in findings if finding.severity == ERROR]
    warnings = [finding for finding in findings if finding.severity == WARNING]
    for finding in findings:
        print(finding.render(), file=stderr)
    print(
        f"init: {created} created, {kept} kept, "
        f"{len(errors)} error(s), {len(warnings)} warning(s)",
        file=stdout,
    )
    return EXIT_ERROR if errors else EXIT_OK


def _ensure_dir(path):
    """Create `path` as a directory if missing. Returns `(item, outcome, finding)`."""
    location = path.as_posix()
    if path.exists():
        return location, "kept", None
    try:
        path.mkdir(parents=True)
    except OSError as error:
        return location, None, Finding(
            ERROR, location, "create", f"directory could not be created: {error}"
        )
    return location, "created", None


def _ensure_file(path, content):
    """Write `content` to `path` if missing. Returns `(item, outcome, finding)`."""
    location = path.as_posix()
    if path.exists():
        return location, "kept", None
    try:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
    except OSError as error:
        return location, None, Finding(
            ERROR, location, "create", f"file could not be created: {error}"
        )
    return location, "created", None


def _sync_symlink(raw_path, stdout):
    """Make `raw_path` a symlink to this project's `memory/`, without deleting data.

    - Missing: create the symlink (making parent directories as needed).
    - Already a symlink (even broken, even pointing elsewhere): re-point it --
      re-pointing a symlink never destroys data, unlike replacing a real path.
    - A real path: handed to `adopt.take_over`, which either frees it (by
      absorbing the agent memory it holds and parking the original aside) or
      refuses and says why. Only a freed path gets a symlink.

    Any OS-level failure along this path (permissions, a dangling parent,
    ...) is reported the same way: a WARNING that never gates, because a
    startup hook built on `init` must never break the session over a symlink.
    """
    path = Path(raw_path)
    location = path.as_posix()
    target = Path("memory").resolve()
    try:
        if path.is_symlink():
            if path.resolve() == target:
                print(f"init: kept symlink {location}", file=stdout)
                return []
            path.unlink()
            path.symlink_to(target, target_is_directory=True)
            print(f"init: re-pointed symlink {location} -> {target}", file=stdout)
            return []
        # A real path that is not a symlink: `adopt` decides whether it holds
        # agent memory this project can absorb, or must be left alone.
        findings = []
        if path.exists():
            freed, findings = adopt.take_over(path, target, stdout)
            if not freed:
                return findings
        path.parent.mkdir(parents=True, exist_ok=True)
        path.symlink_to(target, target_is_directory=True)
        print(f"init: created symlink {location} -> {target}", file=stdout)
        return findings
    except OSError as error:
        message = f"could not be linked to '{target}': {error}; session unaffected"
        return [Finding(WARNING, location, "symlink", message)]
