"""The `init` subcommand: scaffold the adopter layout.

`init` creates the minimal layout for both layers -- curated knowledge and
agent memory -- plus the adopter's configuration and a valid declared
extension stub, so that `validate` and `lint` pass clean right after a run on
an empty project. Every item is created only if missing: an existing item is
left untouched, never overwritten or deleted, and `init` says which of the
two happened.

With `--harness-memory PATH`, `init` also makes PATH a move-proof symlink to
this project's `memory/` directory (absolute target). That is the data half
of the harness integration: computing PATH from the harness's own layout and
calling `init --harness-memory PATH` on every session start is the plugin's
startup hook, wired in a later ticket. `init` only guarantees that calling it
again -- from the same checkout or from a renamed or re-cloned one -- restores
the link without ever deleting data.

When PATH is a real path that is not a symlink, `adopt` decides: a directory
recognizably holding the harness's own agent memory is absorbed into this
project's `memory/` and parked aside as a `.bak` before the link is created
(see `adopt.py`); anything else is left alone with a WARNING saying why. Both
outcomes are fail-open, so a startup hook built on top of `init` can never
break the session.

With `--view`, `init` also creates `knowledge.html` and `memory.html` --
once each. The views are optional, and activation is the presence of the
artifact, not a configuration key (an unknown field in `validated-memory.md`
is an ERROR that gates the other subcommands, so a key would brick an
adopter's project rather than just leave the view inactive). This is why
`--view` only ever creates: an artifact that already exists, even one
edited by hand, is reported `kept` and left untouched, same as every other
item `init` manages -- regenerating what is already there is `render`'s job
(`render --only-existing`, wired to a `SessionStart` hook), not `init`'s. A
corpus the renderer refuses is a WARNING here, never a gate: `init --view`
simply creates nothing this run.
"""

import os
from pathlib import Path

from . import adopt, journal, render
from .findings import ERROR, EXIT_ERROR, EXIT_OK, WARNING, Finding

MEMORY_INDEX = """\
# Agent memory

No entries yet.
"""

CONFIG = """\
---
extension:
  schema: knowledge-extension.md
  version: "1"
id_prefix: kb-
probes:
  git_ref: python3 -m validated_memory.probes.git_ref
---

# Adopter configuration

This file configures how `validated-memory` treats this repository. It is
plain Markdown with a YAML-subset frontmatter, readable without the plugin
installed.

- `extension` names the adopter's declared extension: the schema file
  (`schema`) and the version of it this project is on (`version`). See
  `knowledge-extension.md`.
- `id_prefix` records the id scheme curated-knowledge units follow, for
  humans and skills; `validate` does not enforce it.
- `probes` maps an anchor `kind` to the command that probes it for
  freshness. `git_ref` ships with the plugin as
  `python3 -m validated_memory.probes.git_ref`.

Generated by `validated-memory init`. Safe to hand-edit -- `init` never
overwrites a file that already exists.
"""

EXTENSION_STUB = """\
---
fields: []
---

# Declared extension

This is the adopter's curated-knowledge schema: it declares the fields a
unit's frontmatter may carry, on top of the base contract (`id`, `evidence`,
`supersedes`, `anchors`, `provenance`, `rationale`). No fields are declared yet
(`fields: []`) -- `validate` still enforces the base contract alone until you
add some.

Add a field as an entry under `fields`:

```yaml
fields:
  - name: domain      # the frontmatter key a unit may carry
    type: enum        # 'string' (any non-empty scalar) or 'enum' (closed domain)
    values:           # required only for type 'enum'
      - network
      - storage
  - name: owner
    type: string
```

## Versioning

`version`, in `validated-memory.md`, records which schema version this
project is on. Additive changes (a new field, a new enum value) do not bump
the version; removing or narrowing does. Units already written are never
rewritten to a newer schema -- supersede them instead.

Generated by `validated-memory init`. Safe to hand-edit -- `init` never
overwrites a file that already exists.
"""


def run(harness_memory, view, stdout, stderr):
    """Scaffold the adopter layout under the working directory.

    Returns an exit code: 0 unless an item could not be created. Even a
    harness-memory symlink `init` cannot restore is a WARNING, not an ERROR
    -- fail-open, so the caller (eventually a startup hook) never breaks the
    session over it. Same for `view`: a corpus the renderer refuses is a
    WARNING, never a gate -- see `_ensure_views`.
    """
    findings = []
    created = 0
    kept = 0

    # Everything that journals -- the scaffold and the harness symlink -- runs
    # under one lock for the whole run: `init` is deliberately re-runnable at
    # session start, and two concurrent runs on a brand-new adopter must not
    # be able to mint two adoption ids.
    try:
        with journal.Lock():
            session = journal.Run()
            # Each call below runs (and creates its item, if missing)
            # immediately; this just names the completed results before
            # reporting them in order.
            steps = (
                _ensure_dir(Path("knowledge"), session),
                _ensure_dir(Path("memory"), session),
                _ensure_file(
                    Path("memory") / "MEMORY.md", MEMORY_INDEX, session
                ),
                _ensure_file(Path("validated-memory.md"), CONFIG, session),
                _ensure_file(
                    Path("knowledge-extension.md"), EXTENSION_STUB, session
                ),
            )

            for item, outcome, finding in steps:
                if finding is not None:
                    findings.append(finding)
                    continue
                print(f"init: {outcome} {item}", file=stdout)
                if outcome == "created":
                    created += 1
                else:
                    kept += 1

            if harness_memory is not None:
                findings.extend(_sync_symlink(harness_memory, stdout, session))
    except journal.JournalError as error:
        where = journal.JOURNAL_FILENAME
        location = where if error.lineno is None else f"{where}:{error.lineno}"
        print(
            Finding(ERROR, location, "journal", error.message).render(),
            file=stderr,
        )
        print(
            "init: 0 created, 0 kept, 1 error(s), 0 warning(s)", file=stdout
        )
        return EXIT_ERROR
    except OSError as error:
        # The lock and the journal's own bootstrap both need to create
        # `.validated-memory/` and `journal.jsonl` before any scaffold item
        # is attempted; an adopter root that cannot be written to at all
        # (e.g. read-only permissions) fails here first, ahead of any
        # per-item ERROR `_ensure_dir`/`_ensure_file` would otherwise raise.
        print(
            Finding(
                ERROR,
                journal.JOURNAL_FILENAME,
                "journal",
                f"journal could not be opened: {error}",
            ).render(),
            file=stderr,
        )
        print(
            "init: 0 created, 0 kept, 1 error(s), 0 warning(s)", file=stdout
        )
        return EXIT_ERROR

    if view:
        view_created, view_kept, view_findings = _ensure_views(stdout)
        created += view_created
        kept += view_kept
        findings.extend(view_findings)

    errors = [finding for finding in findings if finding.severity == ERROR]
    warnings = [finding for finding in findings if finding.severity == WARNING]
    for finding in findings:
        print(finding.render(), file=stderr)
    print(
        f"init: {created} created, {kept} kept, "
        f"{len(errors)} error(s), {len(warnings)} warning(s)",
        file=stdout,
    )
    return EXIT_ERROR if errors else EXIT_OK


def _ensure_dir(path, session):
    """Create `path` as a directory if missing. Returns `(item, outcome, finding)`.

    A directory that is already there is recorded as an observation: that it
    pre-existed is a fact about the state before adoption, and nothing can
    re-derive it later.
    """
    location = path.as_posix()
    if path.exists():
        session.observe(location, "directory already present")
        return location, "kept", None
    try:
        path.mkdir(parents=True)
    except OSError as error:
        return location, None, Finding(
            ERROR, location, "create", f"directory could not be created: {error}"
        )
    # `mkdir` is not a file write and has no preimage, so the created case
    # carries no transaction -- but its inverse belongs in the op, not in
    # prose.
    session.append_op(journal.CREATE, "init", location, "directory created")
    return location, "created", None


def _ensure_file(path, content, session):
    """Write `content` to `path` if missing. Returns `(item, outcome, finding)`."""
    location = path.as_posix()
    if path.exists():
        session.observe(location, "file already present")
        return location, "kept", None
    try:
        session.write(location, content, "init")
    except OSError as error:
        return location, None, Finding(
            ERROR, location, "create", f"file could not be created: {error}"
        )
    return location, "created", None


def _sync_symlink(raw_path, stdout, session):
    """Make `raw_path` a symlink to this project's `memory/`, without deleting data.

    - Missing: create the symlink (making parent directories as needed).
    - Already a symlink (even broken, even pointing elsewhere): re-point it --
      re-pointing a symlink never destroys data, unlike replacing a real path.
    - A real path: handed to `adopt.take_over`, which either frees it (by
      absorbing the agent memory it holds and parking the original aside) or
      refuses and says why. Only a freed path gets a symlink.

    Any OS-level failure along this path (permissions, a dangling parent,
    ...) is reported the same way: a WARNING that never gates, because a
    startup hook built on `init` must never break the session over a symlink.

    `raw_path` is outside the repository root, so its record can only ever
    live in the vault (`durability=journal.LOCAL`) -- a repository record may
    never carry an absolute path (ADR 0008, design §7). The previous target
    is read before the link is touched: once it is re-pointed, its former
    target is gone, which is the preimage problem in miniature.
    """
    path = Path(raw_path)
    location = path.as_posix()
    target = Path("memory").resolve()
    previous = os.readlink(path) if path.is_symlink() else None
    try:
        if path.is_symlink():
            if path.resolve() == target:
                print(f"init: kept symlink {location}", file=stdout)
                return []
            path.unlink()
            path.symlink_to(target, target_is_directory=True)
            session.append_op(
                journal.LINK,
                "init",
                path.as_posix(),
                f"previous target: {previous}" if previous else "no previous link",
                durability=journal.LOCAL,
            )
            print(f"init: re-pointed symlink {location} -> {target}", file=stdout)
            return []
        # A real path that is not a symlink: `adopt` decides whether it holds
        # agent memory this project can absorb, or must be left alone.
        findings = []
        if path.exists():
            freed, findings = adopt.take_over(path, target, stdout)
            if not freed:
                return findings
        path.parent.mkdir(parents=True, exist_ok=True)
        path.symlink_to(target, target_is_directory=True)
        session.append_op(
            journal.LINK,
            "init",
            path.as_posix(),
            f"previous target: {previous}" if previous else "no previous link",
            durability=journal.LOCAL,
        )
        print(f"init: created symlink {location} -> {target}", file=stdout)
        return findings
    except OSError as error:
        message = f"could not be linked to '{target}': {error}; session unaffected"
        return [Finding(WARNING, location, "symlink", message)]


def _ensure_views(stdout):
    """Create `knowledge.html` and `memory.html` once each.

    Returns `(created, kept, findings)`, mirroring `_sync_symlink`'s shape
    so `run` folds it into the same counters and prints every finding
    exactly once, from its own central loop -- `build_artifacts` returns
    findings rather than printing them, precisely so a caller like this one
    is never in the position of also having something to print itself.

    Same contract as every other item `init` manages: an artifact that
    already exists is reported `kept` and never touched, hand-edited or not.
    Only a missing artifact triggers a build, and that build goes through
    `render.build_artifacts` -- the one place page composition lives, so
    `init --view`, `render`, and the `--only-existing` startup hook never
    each grow their own copy of it. Both artifacts are built together (one
    `build_artifacts` call covers whichever are missing) before either is
    written, matching `render`'s own all-or-nothing write order.

    A corpus `build_artifacts` refuses is folded into the returned findings
    as a WARNING -- `downgrade=True`, the same fail-open mode `render
    --only-existing` uses -- and creates neither artifact; whichever of the
    two already existed is still reported `kept`.

    A write that fails at the OS level (permissions, a full disk, ...) is,
    like `--harness-memory`, a WARNING rather than a crash or a gate: an
    optional flag doing extra work must never break the rest of `init`'s
    run over it. The write itself is atomic -- a temporary file, then a
    rename, the same shape `render.write_if_changed` uses -- so a failure
    can never leave a truncated page that the next run reports `kept`.

    A broken symlink is the one shape `Path.exists()` reads as absent while
    something is plainly there: writing would follow it and create a file
    wherever it points, outside `init`'s remit. It gets a WARNING and is
    left untouched -- the posture `--harness-memory` takes with a path that
    is anything else real.
    """
    created = 0
    kept = 0
    findings = []
    missing = [
        name
        for name in render.ARTIFACTS
        if not (Path(name).is_symlink() or Path(name).exists())
    ]
    artifacts = {}
    if missing:
        artifacts, build_findings, ok = render.build_artifacts(downgrade=True)
        findings.extend(build_findings)
        if not ok:
            artifacts = {}
    for name in render.ARTIFACTS:
        path = Path(name)
        if path.is_symlink() and not path.exists():
            findings.append(
                Finding(
                    WARNING, name, "create",
                    "exists as a broken symlink; writing would follow it "
                    "and create a file wherever it points, so init leaves "
                    "it untouched",
                )
            )
            continue
        if path.exists():
            print(f"init: kept {name}", file=stdout)
            kept += 1
            continue
        if name not in artifacts:
            continue
        temporary = path.with_name(f"{path.name}.{os.getpid()}.tmp")
        try:
            temporary.write_text(artifacts[name], encoding="utf-8")
            os.replace(temporary, path)
        except OSError as error:
            try:
                temporary.unlink()
            except OSError:
                pass
            findings.append(
                Finding(
                    WARNING, name, "create",
                    f"file could not be created: {error}",
                )
            )
            continue
        print(f"init: created {name}", file=stdout)
        created += 1
    return created, kept, findings
